application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      my-commerce-extension:
        license: Apache-2.0
        actions:
          product-enrichment:
            function: actions/product-enrichment/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: info
              COMMERCE_STORE_CODE: default
              COMMERCE_API_BASE_URL: https://na1-sandbox.api.commerce.adobe.com/XXDjJ3T5pnSP5i9jdkXtSD
              IMS_OAUTH_S2S_ORG_ID: B139231C6912285C0A495FBE@AdobeOrg
              IMS_OAUTH_S2S_CLIENT_ID: 540f2d898de644bd908a06b99405de3e
              IMS_OAUTH_S2S_CLIENT_SECRET: p8e-ynun8jsgJvsa7le-YH7wGr7LeKk-EAju
              IMS_OAUTH_S2S_SCOPES: AdobeID, openid, read_organizations, additional_info.projectedProductContext, additional_info.roles, adobeio_api, read_client_secret, manage_client_secrets, event_receiver_api, commerce.accs, profile, email, org.read
              IMS_TOKEN_URL: https://ims-na1.adobelogin.com/ims/token/v2
            annotations:
              require-adobe-auth: false
              final: true
              include-ims-credentials: true